copy project
osekine/ya_Homework pull request #1
Opened 2024-06-22 20:00 UTC by osekine

2024-06-24 11:26 UTC, truefalsemary requested changes

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/add_chore/presentation/screens/new_chore.dart
> +              Navigator.pop(context);
лучше использовать Navigator.maybePop так как с pop небезопасное удаление

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/add_chore/presentation/screens/new_chore.dart
> +                    style: TextStyles.button, color: Colors.blue)),
для более красивого форматирования можно поставить запятую между Colors.blue

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/add_chore/presentation/widgets/chose_date_widget.dart
> +                    style: TextStyles.body, color: colors.onBackground)),
аналогично, для более красивого форматирования можно поставить запятую между colors.onBackground

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/add_chore/presentation/widgets/chose_date_widget.dart
> +                      style: TextStyles.body, color: colors.primary)),
аналогично, для более красивого форматирования можно поставить запятую между colors. primary

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/add_chore/presentation/widgets/chose_date_widget.dart
> +                dateActive = false;
возможно лучше убрать параметр dateActive, так как можно просто проверять date==null или нет

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/add_chore/presentation/widgets/chose_date_widget.dart
> +              dateActive = value;
зачем `dateActive = value` если потом идет приравнивание `dateActive = date != null`

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/add_chore/presentation/widgets/delete_description_widget.dart
> +                borderRadius: BorderRadius.all(Radius.circular(8.0))),
аналогично, для более красивого форматирования можно поставить запятую после запятую borderRadius поставить

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/add_chore/presentation/widgets/description_widget.dart
> +          style: TextStyles.body, color: colors.onBackground),
аналогично, для более красивого форматирования можно поставить запятую после запятую colors. onBackground

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/add_chore/presentation/widgets/description_widget.dart
> +            Radius.circular(8),
здесь наоборот лишняя запятая после radius

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/add_chore/presentation/widgets/priority_widget.dart
> +    final Map<Priority, String> priorityName = {
не очень хорошо прописывать логику в билде, вообще можно просто нацепить extension на enum Priority, в котором добавить функцию через свич, которая и будет мапить приоритеты со строками

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/domain/chore_list_provider.dart
> +  final VoidCallback onToggleVisible;
`onToggleVisible` не используется

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/domain/chore_list_provider.dart
> +    return isDoneVisible != oldWidget.isDoneVisible ||
немного странное обновление, только по количеству тасок и фильтру, возможно стоит еще добавить сравнение по chores, но это нужно будет делать через ListEquality из collections, потому что простое сравнение списков не будет работать, из-за того что они являются объектами и у каждого свой хеш и даже с одинаковыми элементами сравнение через оператор == равенство не подтвердит

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/screens/home.dart
> +  late final ScrollController _controller;
не диспозтся контроллер, важно исправить этот момент, чтобы не допустить утечек памяти

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/screens/home.dart
> +  void toggleVisible() {
Лучше следовать этому порядку, дабы не вносить путаницу
<img width="948" alt="Screenshot 2024-06-24 at 13 49 53" src="https://github.com/osekine/ya_Homework/assets/94931275/fa14c04a-02bc-45dc-b8ae-6bdef7353168">

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/screens/home.dart
> +                  builder: ((context) => const NewChoreScreen())));
возможно стоит рассмотреть вариант с именновованными роутаами

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore.dart
> +  @override
нет пробела между методами и билдом, ухудшает читаемость

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore.dart
> +Widget _getChore(BuildContext context, Chore chore) {
возможно лучше передавать сразу colors без контекста, так как контекст нигде не используется

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore.dart
> +                style: TextStyles.body, color: colors.onBackground),
запятая после colors.onBackground

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore.dart
> +                style: TextStyles.body, color: colors.onBackground),
запятая после colors.onBackground

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore.dart
> +  if (chore.priority == Priority.high) {
с if не очень читаемо, возможно лучше использовать switch, потому что тут идет проверка значений enum

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore_list_body_widget.dart
> +                                'Новое',
лишняя запятая после 'Новое'

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore_title_appbar.dart
> +class ChoreTitleAppbar extends StatefulWidget {
а зачем `StatefulWidget `, если setState нигде не используется и только билдом пользуешься?

2024-06-24 11:26 UTC, truefalsemary commented on lib/models/chore.dart
> +  Chore(
можно const добавить и лучше конструктор выше делать переменных

2024-06-24 11:26 UTC, truefalsemary commented on lib/utils/format.dart
> +  return '${date.day} ${months[date.month.toInt()]} ${date.year}';
если потом будешь делать локализацию, то можно отказаться от этого момента и использовать DateFormat из intl вот в таком виде: `DateFormat('dd MMMM yyyy').format(dateTime)`

2024-06-24 11:26 UTC, truefalsemary commented on lib/models/chore.dart
> +      this.priority = Priority.none});
также проблемы с форматированием

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/visibility_widget.dart
> +    super.key,
можно убрать запятую после ключа для лучшей читаемости

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore.dart
> +      background: Container(
если меняешь только цвет, то можно использовать `ColoredBox` вместо `Container`

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore.dart
> +      secondaryBackground: Container(
аналогично можно использовать ColoredBox вместо Container

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore_list_body_widget.dart
> +class ChoreListBodyWidget extends StatelessWidget {
еще момент, если этот виджет используется только на главной странице, то только главная страница и должна о нем знать, поэтому возможно лучше сделать приватными и файл part of главной страницы

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore_title_appbar.dart
> +class ChoreTitleAppbar extends StatefulWidget {
аналогично лучше сделать приватным и частью файла страницы, на которой используется

2024-06-24 11:26 UTC, truefalsemary commented on lib/models/chore.dart
> +List<Chore> dumbell = [
а еше можно сделать const  этот List и назвать dumbells, все-таки их тут много и можно реально накачаться))

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore_title_appbar.dart
> +    final controller = ChoreListProvider.of(context).scrollController;
теперь понятно почему statefull, возможно лучше объявить этот controller в initState и не забыть потом задиспозить

2024-06-24 11:26 UTC, truefalsemary commented on lib/features/manage_chores/presentation/widgets/chore_title_appbar.dart
> +      controller.addListener(() {
добавлять слушателя в билде кажется не очень правильно, можно сделать это в `initState`, но обязательно обернув  в `WidgetsBinding.instance.addPostFrameCallback`, также возможно добавить `didChangeDependencies `

2024-06-24 12:57 UTC, osekine commented on lib/utils/format.dart
> +  return '${date.day} ${months[date.month.toInt()]} ${date.year}';
У ментора уточнял насчет intl, так как это сторонний пакет. Он сказал что не уверен. Я не стал ждать уточнений и просто сделал своё форматирование

2024-06-25 15:24 UTC, osekine commented on lib/features/manage_chores/domain/chore_list_provider.dart
> +  final VoidCallback onToggleVisible;
onToggleVisible нужен, чтобы VisibilityWidget ниже по дереву мог вызвать ребилд экрана

2024-06-26 19:46 UTC, aNOOBisTheGod commented
Cпасибо большое, что выложил билд в релизы - очень удобно скачивать!

2024-06-26 19:49 UTC, aNOOBisTheGod commented
При свайпе Dismissible-виджета, контент контейнера выходит за пределы списка, оберни карточку в ClipRRect

2024-06-26 19:52 UTC, aNOOBisTheGod commented
Логгер лучше в отдельный класс вынести и сделать отдельные методы для каждого места, где информацию будешь логгировать, а-ля TaskLogger.newTaskAdded()

2024-06-26 19:53 UTC, aNOOBisTheGod commented
Тема приложения не меняется если переключать тему в настройках телефона

2024-06-26 19:54 UTC, aNOOBisTheGod commented on lib/main.dart
> +      theme: darkTheme,
вот тут нужно задать светлую тему, а также добавить параметр darkTheme - и там уже задать темную

2024-06-26 19:58 UTC, aNOOBisTheGod commented
Также нет логики просмотра заметок, тыкал и на иконку, и на саму карточку - ничего

2024-06-29 17:26 UTC, osekine commented
> При свайпе Dismissible-виджета, контент контейнера выходит за пределы списка, оберни карточку в ClipRRect

Спасибо, полезная инфа

2024-06-29 17:27 UTC, osekine commented
> Также нет логики просмотра заметок, тыкал и на иконку, и на саму карточку - ничего

Такой задачи не стояло изначально, логику не прописывал

2024-06-29 17:28 UTC, osekine commented
> Тема приложения не меняется если переключать тему в настройках телефона

Опять же, такого в условии задания не было

2024-06-29 17:28 UTC, osekine commented on lib/main.dart
> +      theme: darkTheme,
Спасибо, буду знать)

2024-06-29 18:12 UTC, aNOOBisTheGod commented
> > Также нет логики просмотра заметок, тыкал и на иконку, и на саму карточку - ничего
> 
> Такой задачи не стояло изначально, логику не прописывал

да, конкретно формулировки не было с тем, что нужно сделать редактирование задачи, но это, по сути, примерно то же самое, что и не сделать навигацию по кнопке с плюсиком. было бы неплохо добавить в общем)

2024-06-29 18:14 UTC, aNOOBisTheGod commented
> > Тема приложения не меняется если переключать тему в настройках телефона
> 
> Опять же, такого в условии задания не было

в макете есть две темы, ошибка не критическая, но тему сделать вроде бы не так сложно, поэтому хорошо бы было реализовать

2024-06-29 20:18 UTC, usermaryz reviewed
Код легко читается, приятно видеть отдельные виджеты на каждую из подзадач)

2024-06-29 20:18 UTC, usermaryz commented on lib/features/add_chore/presentation/screens/new_chore.dart
> +                    style: TextStyles.button, color: Colors.blue)),
На будущее, так как нужно будет подключение различных языков, заменила бы жестко заданные строки ('Сохранить', 'Что надо сделать...') на локализованные строки

2024-06-29 20:18 UTC, usermaryz commented on lib/features/add_chore/presentation/widgets/description_widget.dart
> +            Radius.circular(8),
На будущее, так как нужно будет подключение различных языков, заменила бы жестко заданные строки ('Сохранить', 'Что надо сделать...') на локализованные строки

2024-06-29 20:18 UTC, usermaryz commented on lib/features/manage_chores/presentation/widgets/chore_list_body_widget.dart
> +                                'Новое',
На будущее, так как нужно будет подключение различных языков, заменила бы жестко заданные строки ('Сохранить', 'Что надо сделать...') на локализованные строки

2024-06-29 20:18 UTC, usermaryz commented on pubspec.yaml
> +  # see https://flutter.dev/custom-fonts/#from-packages
для того чтобы иконка отображалась на любых платформах, можно рассмотреть решение с помощью flutter_launcher_icons, и кучу картинок для Android не надо будет загружать

2024-07-10 23:45 UTC, merged